### ISSUE TITLE
Versie 1.9.1.0

### ISSUE THREAD

**Issue by PieterCappelle** [ho-nl/Ho_nl_NL#61]
Hallo,

Ik merk dat de nieuwe translation-tags die gebruikt worden in de nieuwe versie 1.9.1.0 nog niet in deze versie zijn opgenomen. Moet dit manueel gebeuren of gebruiken jullie hiervoor een script?

Pieter

**Comment by cjwijtmans** [comment]
Ik zie alleen een master branche. Ik heb de nl_NL folder in locale gezet naast en_US en de locale in magento admin op nederlands gezet. Het werkt voor mij niet. (Zit op magento 1.9.1.0).

**Comment by paales** [comment]
@cjwijtmans Dit issue is dan ook nog niet op gepakt.

**Comment by cjwijtmans** [comment]
Als ik de translate tooltje gebruik zou het dan wel werken?

**Comment by paales** [comment]
@cjwijtmans Zou je een los issue willen aanmaken? Ik begrijp niet geheel waar je problemen mee hebt. Deze discussie gaat over nieuwe features geïmplementeerd in 1.9.1.0, niet over installatie issues met 1.9.1.0 :smile:

**Comment by royduin** [comment]
Voor 1.9.1.0 gewoon de master branch pakken? Er is nog geen aparte branch...

**Comment by cjwijtmans** [comment]
Ja werkt wel roy. Er zijn wel een paar vertalingen die er niet instaan.

**Comment by royduin** [comment]
Dien ik de merge.php ook te draaien? Mail templates etc gaan prima?

**Comment by cjwijtmans** [comment]
Heb ik niet gedaan, Mails heb ik ook nog niet getest..


Live long and prosper,

Christ-Jan Wijtmans
https://github.com/cjwijtmans
http://facebook.com/cj.wijtmans
http://twitter.com/cjwijtmans

**Comment by macrel** [comment]
Hoi,

is dit gerelateerd aan mijn probleem hier: https://github.com/ho-nl/Ho_nl_NL/issues/69 

Is er al een oplossing voor? Als ik de laatste versie van jullie vertalingen download dan zie ik niet die {{template config_path="design/email/header"}} e.d. staan? Ik vermoed dat het daarom fout gaat, want dit staat wel in de core Magento translaties.

Is er een kant-en-klaar package voor magento 1.9 die ik zoals bij 1.8 kan uploaden zodat alles werkt? 

Hopelijk kan iemand me helpen! Bedankt!

**Comment by hostep** [comment]
@macrel: je kan voorlopig de fork van hslatman gebruiken, wij doen dit ook al een paar maanden: https://github.com/hslatman/Ho_nl_NL/tree/magento_191_responsive_mails

@paales: zou je het zien zitten om eens een branch op te zetten voor Magento 1.9.1.0 met PR https://github.com/ho-nl/Ho_nl_NL/pull/60? Zou fantastisch zijn. Ondertussen is Magento 1.9.1.0 al een heel tijd geleden verschenen en zijn er al vrij veel webshops die op die versie draaien. Thanks!

**Comment by macrel** [comment]
Bedankt! Ik ga dat testen

 

Van: Pieter Hoste [mailto:notifications@github.com] 
Verzonden: vrijdag 17 april 2015 20:38
Aan: ho-nl/Ho_nl_NL
CC: macrel
Onderwerp: Re: [Ho_nl_NL] Versie 1.9.1.0 (#61)

 

@macrel <https://github.com/macrel> : je kan voorlopig de fork van hslatman gebruiken, wij doen dit ook al een paar maanden: https://github.com/hslatman/Ho_nl_NL/tree/magento_191_responsive_mails

@paales <https://github.com/paales> : zou je het zien zitten om eens een branch op te zetten voor Magento 1.9.1.0 met PR #60 <https://github.com/ho-nl/Ho_nl_NL/pull/60> ? Zou fantastisch zijn. Ondertussen is Magento 1.9.1.0 al een heel tijd geleden verschenen en zijn er al vrij veel webshops die op die versie draaien. Thanks!
