### ISSUE TITLE
Magento 1.9.1 pakt vertaling niet op.

### ISSUE THREAD

**Issue by cjwijtmans** [ho-nl/Ho_nl_NL#64]
Heb de nl_NL naast en_US gezet maar magento pakt de vertaling niet op. Ook heb ik het probleem dat op de backend alles in USD / US$ is terwijl ik overal euro heb ingeschakeld of als de enigste heb ingesteld. Ook op de frontend staat standaard USD aan terwijl ik die niet heb ingeschakeld. Alles staat ook op nederlands ingesteld(locale dus).

**Comment by paales** [comment]
@cjwijtmans Blijkbaar staat er tóch iets niets goed in je configuratie helaas. De currency staat 100% los van de locale.

Zie daarvoor: http://www.magentocommerce.com/knowledge-base/categories/category/managing-currency-rates

Voor het instellen van de vertalingen (als de bestanden inderdaad in app/locale/nl_NL zijn geplaatst):
http://www.magentocommerce.com/knowledge-base/entry/configuration-general-general

**Comment by cjwijtmans** [comment]
Nope config staat goed. Ik maak morgen screenshots.

**Comment by GlobalTit** [comment]
Heb hier net het zelfde probleem, alle instellingen staan goed maar krijg geen NL vertalling

**Comment by GlobalTit** [comment]
Probleem met vertalling inorde hier, hij had niet alle cache geleegd. Na uitloggen en weer inloggen opnieuw alles gewist en terug even uit en weer in gelogd was het inorde.
