### ISSUE TITLE
Inladen van de transactionele e-mail voor handmatige bewerkingen werkt niet meer in 1.9.1

### ISSUE THREAD

**Issue by macrel** [ho-nl/Ho_nl_NL#69]
Bij Magento lager dan 1.9 kon je de transactionele e-mail inladen bij sjablonen, om ze de Nederlandse mailtemplate verder aan te passen. Dit lijkt niet meer te werken in 1.9.1. Engelse laad hij prima in, maar de Nederlandse laat enkel een blanko scherm zien, alle invoer velden blijven dus leeg, waar normaal het template wordt ingeladen.

Om te reproduceren:
- ga naar systeem > e-mail sjablonen
- klik nieuw
- selecteer Nederlands, en bijv. Nieuwe bestelling gast
- Klik op sjabloon inladen

Dit werkt dus (bij mij) niet meer.

**Comment by macrel** [comment]
PS: als ik uit het mapje en_US de template kopieer naar de Nederlandse map, en ik klik dan op inladen, dan laad hij dus wel (de Engelse) in, lijkt dus echt iets fout in het template? Ik heb ze met elkaar vergeleken en zie dat de Engelse wat includes doet met config/header en style.

**Comment by fourroses666** [comment]
Heb je bij configuratie opties wel de juiste sjablonen geselecteerd? bij mij waren er ook een aantal waarbij de standaard werd gekozen terwijl de nieuw aangemaakte gekozen moest worden. Ik weet niet of dit door de update kwam of een eigen fout is geweest.

**Comment by macrel** [comment]
Bedankt voor je reactie! Heb ik gedaan inderdaad, en dat gedeelte gaat opzich prima. Maar wil nu dus zelf een template overschrijven (wat tekst toevoegen, opmaak veranderen). Dat kan normaal door het sjabloon in te laden onder Systeem > Beheer e-mail sjablonen, maar dat gedeelte werkt dus niet meer lijkt het op.
