### ISSUE TITLE
Problemen met Ho_nl_NL

### ISSUE THREAD

**Issue by phroziac** [ho-nl/Ho_nl_NL#70]
Ik heb zojuist via mijn FTP de Ho_nl_NL geinstalleerd.
Nu krijg ik als ik mijn website open 2 drop-down vensters waar ik 1 voor 1 templates moet aanpassen wat nog niet vertaald is of nog het zelfde als het orgineel is.
Ik kan niet bij mijn admin panel komen

Ik kan hier niet verder.. wat nu ?

**Comment by paales** [comment]
@phroziac Even de index.php terug zetten uit je eigen installatie.

Stap twee uit de installatie:

> Kopieer de map /app/locale/nl_NL naar je Magento installatie (als je al een eerdere vertaling hebt geinstalleerd via Magento connect, verwijder deze eerst).

Dus niet alle bestanden naar je installatie kopieren, deze overschrijft namelijk ook je index.php
