### ISSUE TITLE
Magento Connect

### ISSUE THREAD

**Issue by yasinkocak** [ho-nl/Ho_nl_NL#75]
Handig als dit ook in Magento Connect te vinden is makkelijker te updaten toch?

**Comment by tomlankhorst** [comment]
Je kan voor nu de tool 'modman' gebruiken. 
https://github.com/colinmollenhour/modman

Na downloaden kan je Ho_nl_NL installeren: 

``modman init``(eenmalig)
``modman clone https://github.com/ho-nl/Ho_nl_NL.git`` (voor elke module)

Om te updaten: 
``modman update-all``
