### ISSUE TITLE
Sommige dingen worden niet vertaald...

### ISSUE THREAD

**Issue by M-Purple** [ho-nl/Ho_nl_NL#83]
Hi!

Ik heb nog vaak dat bepaalde dingen niet vertaald worden... Als voorbeeld heb ik nu de links bovenin de website met inloggen, winkelwagen, mijn account etc.

Nu blijft My account in het engels staan net zoals Log Out terwijl deze in de Mage_Customer netjes vertaald worden. Kan iemand mij daarmee helpen? :)

Thanks!

![schermafbeelding 2015-09-22 om 08 44 06](https://cloud.githubusercontent.com/assets/14726823/10012225/2bab54e0-6106-11e5-82d2-2d801de80acb.png)

**Comment by Insect2015** [comment]
Hoi M-Purple,

Gebruik je een thema ? Zo ja dan zou je kunnen kijken dat dit in de broncode verkeerd staat.

gr,
Michel

**Comment by tomlankhorst** [comment]
Heb je ten minste het volgende geprobeerd:
1. Alle caches te wissen
2. Valideren of de vertaal-functie is gebruikt in de phtml file ``$this->__("My Account")``
